# Generated by Django 4.1.1 on 2022-09-28 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/doctors'),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='gadress',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='typesofdoctorchoices',
            name='title',
            field=models.CharField(choices=[('General', 'General'), ('DENTIST', 'DENTIST'), ('ALLERGIST', 'ALLERGIST'), ('ANESTHESIOLOGIST', 'ANESTHESIOLOGIST'), ('CARDIOLOGIST', 'CARDIOLOGIST'), ('DERMATOLOGIST', 'DERMATOLOGIST'), ('ENDOCRINOLOGIST', 'ENDOCRINOLOGIST'), ('GASTROENTEROLOGIST', 'GASTROENTEROLOGIST'), ('HEMATOLOGIST', 'HEMATOLOGIST'), ('INFECTIOUS DISEASE SPECIALIST', 'INFECTIOUS DISEASE SPECIALIST'), ('NEPHROLOGIST', 'NEPHROLOGIST'), ('NEUROLOGIST', 'NEUROLOGIST'), ('ONCOLOGIST', 'ONCOLOGIST'), ('OPHTHALMOLOGIST', 'OPHTHALMOLOGIST'), ('ORTHOPEDIC SURGEON', 'ORTHOPEDIC SURGEON'), ('OTOLARYNGOLOGIST', 'OTOLARYNGOLOGIST'), ('PATHOLOGIST', 'PATHOLOGIST'), ('PEDIATRICIAN', 'PEDIATRICIAN'), ('PSYCHIATRIST', 'PSYCHIATRIST'), ('PULMONOLOGIST', 'PULMONOLOGIST'), ('RADIOLOGIST', 'RADIOLOGIST'), ('RHEUMATOLOGIST', 'RHEUMATOLOGIST'), ('UROLOGIST', 'UROLOGIST'), ('VASCULAR SURGEON', 'VASCULAR SURGEON'), ('OTHER', 'OTHER')], max_length=255, verbose_name='title'),
        ),
        migrations.DeleteModel(
            name='DoctorImage',
        ),
    ]
