# Generated by Django 4.1.1 on 2022-09-28 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PatientImage',
        ),
    ]
